name: Deploy ERP to cPanel

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy to cPanel FTP
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Sync files to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: public_html/ 
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env.example
            README.md
            phpunit.xml

      - name: Clear Live Laravel Cache
        run: curl -s https://erp.atikautoricemills.com/auto-deploy-cache-clear/AtikAutoDeploy2026!